Repository IDAES/examples-pse, pull requests merged in 2021-04, with the labels that each got.

#40 Address test failures due to ipopt checks and inconsistent notebook build order
  .github/workflows/main.yml
  build.py
  tests/conftest.py
Labels: Priority:High, bug

#39 Remove CircleCI directory and config file
  .circleci/config.yml
Labels: Priority:Normal

#43 Removing bootstrap from parmest notebooks
  src/Tutorials/Advanced/ParamEst/parameter_estimation_NRTL_using_state_block_solution_testing.ipynb
  src/Tutorials/Advanced/ParamEst/parameter_estimation_NRTL_using_unit_model_solution_testing.ipynb
Labels: Priority:High
