Repository IDAES/examples-pse, pull requests merged in 2021-02, with the labels that each got.

#31 Make DMF examples more robust to Parmest output
  src/Tutorials/Advanced/ParamEst/DMF_for_parameter_estimation_NRTL_using_unit_model_solution_testing.ipynb
Labels: Priority:High, bug

#28 Data quality control example using Pecos
  build.yml
  docs/Examples/Pecos/index.rst
  docs/Examples/index.rst
  notebook_index.yml
  src/Examples/Pecos/data_quality_control_testing.ipynb
  src/Examples/Pecos/simple_data.csv
  src/notebook_index.ipynb
Labels: Priority:Mid

#32 Fix errors in Tutorials/Advanced/ParamEst notebooks
  .github/workflows/main.yml
  build-ci.yml
  src/Tutorials/Advanced/ParamEst/DMF_1_for_parameter_estimation_NRTL_using_unit_model_solution_testing.ipynb
  src/Tutorials/Advanced/ParamEst/DMF_2_flash_unit_Model_with_NRTL_solution_testing.ipynb
Labels: Priority:High
