Repository IDAES/examples-pse, pull requests merged in 2022-05, with the labels that each got.

#110 Add scaling to reduce example runtime
  docs/Examples/Advanced/CustomProperties/index.rst
  notebook_index.yml
  src/Examples/Advanced/CustomProperties/HI_init.json.gz
  src/_skip/HI_init.json.gz
  src/_skip/Hydrocarbon_Processing_example.ipynb
  src/_skip/air_separation_case_study.ipynb
  src/notebook_index.ipynb
Labels: bug, Priority:High

#115 Track import path changes for DMF
  src/Examples/Advanced/DataRecon/boiler_flowsheet_recon_testing.ipynb
  src/Examples/Advanced/DataRecon/econ_parmest_testing.ipynb
  src/Examples/Advanced/DataRecon/econ_recon_testing.ipynb
  src/Examples/Tools/data_management_framework.ipynb
  src/Tutorials/Advanced/ParamEst/DMF_1_for_parameter_estimation_NRTL_using_unit_model_solution_testing.ipynb
  src/Tutorials/Advanced/ParamEst/DMF_2_flash_unit_Model_with_NRTL_solution_testing.ipynb
Labels: Priority:High

#114 Add NGCC + SOEC Flowsheet
  src/Examples/Flowsheets/ngcc/gas_turbine.py
  src/Examples/Flowsheets/ngcc/gas_turbine_init.json.gz
  src/Examples/Flowsheets/ngcc/hrsg.py
  src/Examples/Flowsheets/ngcc/hrsg_init.json.gz
  src/Examples/Flowsheets/ngcc/ngcc.ipynb
  src/Examples/Flowsheets/ngcc/ngcc.py
  src/Examples/Flowsheets/ngcc/ngcc_init.json.gz
  src/Examples/Flowsheets/ngcc/ngcc_soec.ipynb
  src/Examples/Flowsheets/ngcc/ngcc_soec.py
  src/Examples/Flowsheets/ngcc/ngcc_soec_init.json.gz
  src/Examples/Flowsheets/ngcc/soec.py
  src/Examples/Flowsheets/ngcc/soec_flowsheet_costing.py
  src/Examples/Flowsheets/ngcc/soec_init.json.gz
  src/Examples/Flowsheets/ngcc/steam_turbine.py
  src/Examples/Flowsheets/ngcc/steam_turbine_init.json.gz
Labels: Priority:Normal

#91 Add Binder setup files to facilitate debugging
  .binder/README.md
  .binder/apt.txt
  .binder/postBuild
  .binder/requirements.txt
Labels: Priority:Normal
