Repository IDAES/examples-pse, pull requests merged in 2022-12, with the labels that each got.

#167 Fixing broken import and typos
  src/Examples/Flowsheets/HDA_flowsheet_with_costing.ipynb
  src/Examples/Flowsheets/power_generation/supercritical/supercritical_power_plant.ipynb
  src/Examples/Flowsheets/power_generation/supercritical/supercritical_steam_cycle.ipynb
  src/Tutorials/Basics/notebook_test_script.py
Labels: bug, Priority:EXTREME

#160 NGCC + SOEC Assert Solution
  src/Examples/Flowsheets/power_generation/ngcc/NGCC_flowsheet_solution.json.gz
  src/Examples/Flowsheets/power_generation/ngcc/hrsg.py
  src/Examples/Flowsheets/power_generation/ngcc/ngcc_soec.ipynb
  src/Examples/Flowsheets/power_generation/ngcc/ngcc_soec_costing.py
  src/Examples/Flowsheets/power_generation/rsofc/rsofc_soec_flowsheet.py
  src/Examples/Flowsheets/power_generation/rsofc/rsofc_soec_results.svg
Labels: Priority:High

#166 Adding StateJunction & Valve Unit Models into Jupyter Notebook
  docs/Examples/UnitModels/Operations/index.rst
  docs/Examples/UnitModels/Operations/statejunction.svg
  docs/Examples/UnitModels/Operations/valve_1.svg
  notebook_index.yml
  src/Examples/UnitModels/Operations/statejunction.svg
  src/Examples/UnitModels/Operations/statejunction_testing.ipynb
  src/Examples/UnitModels/Operations/valve_1.svg
  src/Examples/UnitModels/Operations/valve_testing.ipynb
  src/notebook_index.ipynb
Labels: Priority:Normal

#165 Adding Separation & Flash Unit Models into Jupyter Notebook
  docs/Examples/UnitModels/Operations/flash.svg
  docs/Examples/UnitModels/Operations/index.rst
  docs/Examples/UnitModels/Operations/splitter.svg
  notebook_index.yml
  src/Examples/UnitModels/Operations/flash.svg
  src/Examples/UnitModels/Operations/flash_testing.ipynb
  src/Examples/UnitModels/Operations/separator_testing.ipynb
  src/Examples/UnitModels/Operations/splitter.svg
  src/notebook_index.ipynb
Labels: Priority:High

#164 Adding sofc flowsheet
  build-ci.yml
  build.yml
  docs/Examples/Flowsheets/power_generation/index.rst
  docs/Examples/Flowsheets/power_generation/sofc/index.rst
  notebook_index.yml
  src/Examples/Flowsheets/power_generation/sofc/data_tabulated/sofc.csv
  src/Examples/Flowsheets/power_generation/sofc/sofc.ipynb
  src/Examples/Flowsheets/power_generation/sofc/sofc.py
  src/Examples/Flowsheets/power_generation/sofc/sofc_costing.py
  src/Examples/Flowsheets/power_generation/sofc/sofc_init.json.gz
  src/Examples/Flowsheets/power_generation/sofc/sofc_rom.py
  src/Examples/Flowsheets/power_generation/sofc/sofc_rom_data.json
  src/Examples/Flowsheets/power_generation/sofc/sofc_template.svg
  src/notebook_index.ipynb
Labels: Priority:High

#163 Adding Missing Units Models into Jupyter Notebook
  docs/Examples/UnitModels/Operations/feed.svg
  docs/Examples/UnitModels/Operations/index.rst
  docs/Examples/UnitModels/Operations/translator.svg
  notebook_index.yml
  src/Examples/UnitModels/Operations/feed.svg
  src/Examples/UnitModels/Operations/feed_flash_testing.ipynb
  src/Examples/UnitModels/Operations/feed_testing.ipynb
  src/Examples/UnitModels/Operations/mixer_testing.ipynb
  src/Examples/UnitModels/Operations/product_testing.ipynb
  src/Examples/UnitModels/Operations/translator.svg
  src/Examples/UnitModels/Operations/translator_testing.ipynb
  src/notebook_index.ipynb
Labels: Priority:High

#170 Standalone soec
  build-ci.yml
  build.yml
  docs/Examples/Flowsheets/power_generation/index.rst
  docs/Examples/Flowsheets/power_generation/soec/index.rst
  src/Examples/Flowsheets/power_generation/soec/soec.ipynb
  src/Examples/Flowsheets/power_generation/soec/soec.py
  src/Examples/Flowsheets/power_generation/soec/soec_flowsheet_costing.py
  src/Examples/Flowsheets/power_generation/soec/soec_standalone_template.svg
  src/notebook_index.ipynb
Labels: Priority:Normal
