Repository IDAES/examples-pse, pull requests merged in 2022-09, with the labels that each got.

#130 Removing deprecations from Tutorials/Advanced
  src/Tutorials/Advanced/ParamEst/DMF_1_for_parameter_estimation_NRTL_using_unit_model_solution_testing.ipynb
  src/Tutorials/Advanced/ParamEst/DMF_2_flash_unit_Model_with_NRTL_solution_testing.ipynb
  src/Tutorials/Advanced/ParamEst/parameter_estimation_NRTL_using_state_block_solution_testing.ipynb
  src/Tutorials/Advanced/ParamEst/parameter_estimation_NRTL_using_unit_model_solution_testing.ipynb
Labels: bug, Priority:Normal

#129 Fixing deprecations in /skip and /Tutorials/Basics
  src/Tutorials/Basics/HDA_flowsheet_solution_testing.ipynb
  src/Tutorials/Basics/Hydrodealkylation.json
  src/Tutorials/Basics/flash_unit_solution_testing.ipynb
  src/Tutorials/Basics/visualizer_tutorial.ipynb
  src/Tutorials/Basics/visualizer_tutorial.py
  src/_skip/Hydrocarbon_Processing_example.ipynb
  src/_skip/air_separation_case_study.ipynb
Labels: bug, Priority:Normal

#132 Cleaning up more deprecation warnings
  src/Examples/Advanced/CustomProperties/Dictionary_Txy_diagrams.ipynb
  src/Examples/Advanced/CustomProperties/Parameter_estimation_PR.ipynb
  src/Examples/Advanced/CustomProperties/custom_physical_property_packages_testing.ipynb
  src/Examples/Advanced/CustomProperties/custom_reaction_property_packages_testing.ipynb
  src/Examples/Advanced/CustomProperties/thermophysical_property_example.py
  src/Examples/Advanced/CustomUnitModels/custom_compressor_testing.ipynb
  src/Examples/Advanced/CustomUnitModels/custom_heater_testing.ipynb
  src/Examples/Advanced/DataRecon/boiler_data_rec.py
  src/Examples/Advanced/DataRecon/boiler_flowsheet_recon_testing.ipynb
  src/Examples/Advanced/DataRecon/boiler_scpc_init.svg
  src/Examples/Advanced/DataRecon/optimal_run.json.gz
  src/Examples/Tools/data_management_framework.ipynb
  src/Examples/UnitModels/Operations/compressor_testing.ipynb
  src/Examples/UnitModels/Operations/heater_testing.ipynb
  src/Examples/UnitModels/Operations/mixer_testing.ipynb
  src/Examples/UnitModels/Operations/pump_testing.ipynb
  src/Examples/UnitModels/Operations/skeleton_unit_testing.ipynb
  src/Examples/UnitModels/Operations/turbine_testing.ipynb
  src/Examples/UnitModels/Reactors/cstr_testing.ipynb
  src/Examples/UnitModels/Reactors/equilibrium_reactor_testing.ipynb
  src/Examples/UnitModels/Reactors/gibbs_reactor_testing.ipynb
  src/Examples/UnitModels/Reactors/plug_flow_reactor_testing.ipynb
  src/Examples/UnitModels/Reactors/stoichiometric_reactor_testing.ipynb
Labels: bug, documentation, Priority:High

#131 Update example notebooks with new HX naming conventions
  src/Examples/Advanced/DataRecon/boiler_data_rec.py
  src/Examples/Advanced/DataRecon/boiler_flowsheet_recon_testing.ipynb
  src/Examples/Advanced/DataRecon/econ_init.json.gz
  src/Examples/Advanced/DataRecon/econ_init.svg
  src/Examples/Advanced/DataRecon/econ_parmest_testing.ipynb
  src/Examples/Advanced/DataRecon/econ_recon.csv
  src/Examples/Advanced/DataRecon/econ_recon_testing.ipynb
  src/Examples/Flowsheets/methanol_synthesis.ipynb
  src/Examples/Flowsheets/ngcc/gas_turbine.py
  src/Examples/Flowsheets/ngcc/hrsg.py
  src/Examples/Flowsheets/ngcc/ngcc.ipynb
  src/Examples/Flowsheets/ngcc/ngcc.py
  src/Examples/UnitModels/Operations/heat_exchanger_0D_testing.ipynb
Labels: bug, Priority:High

#134 Fixing deprecated import in PySMO notebook
  src/Examples/SurrMod/PySMO/PySMO_basics.ipynb
Labels: bug, Priority:High

#135 NGCC/SOEC Example Flowsheets Update
  src/Examples/Flowsheets/HDA_flowsheet_with_distillation_solution_testing.ipynb
  src/Examples/Flowsheets/ngcc/gas_turbine.py
  src/Examples/Flowsheets/ngcc/gas_turbine_init.json.gz
  src/Examples/Flowsheets/ngcc/hrsg.py
  src/Examples/Flowsheets/ngcc/hrsg_init.json.gz
  src/Examples/Flowsheets/ngcc/ngcc.ipynb
  src/Examples/Flowsheets/ngcc/ngcc_init.json.gz
  src/Examples/Flowsheets/ngcc/ngcc_soec.ipynb
  src/Examples/Flowsheets/ngcc/ngcc_soec_costing.py
  src/Examples/Flowsheets/ngcc/soec.py
  src/Examples/Flowsheets/ngcc/soec_init.json.gz
  src/Examples/Flowsheets/ngcc/steam_turbine.py
  src/Examples/Flowsheets/ngcc/steam_turbine_init.json.gz
Labels: bug, Priority:High

#136 Fixing another deprecation
  src/Examples/Advanced/DataRecon/boiler_flowsheet_recon_testing.ipynb
Labels: Priority:High

#138 Fixing deprecated import in HDA w/ distil example
  src/Examples/Flowsheets/hda_ideal_VLE.py
Labels: Priority:Normal

#141 Cleaning up use of old tagging functions in examples
  src/Examples/Advanced/DataRecon/boiler_flowsheet_recon_testing.ipynb
  src/Examples/Advanced/DataRecon/boiler_scpc_init.svg
  src/Examples/Advanced/DataRecon/econ_init.svg
  src/Examples/Advanced/DataRecon/econ_parmest_testing.ipynb
  src/Examples/Advanced/DataRecon/econ_recon_testing.ipynb
  src/Examples/Advanced/DataRecon/optimal_run.json.gz
Labels: bug, Priority:High

#142 Fixing a missed use of old tagging methods
  src/Examples/Advanced/DataRecon/boiler_flowsheet_recon_testing.ipynb
  src/Examples/Advanced/DataRecon/optimal_run.json.gz
Labels: bug, Priority:High

#124 HDA Costing Framework Example
  docs/Examples/Flowsheets/index.rst
  notebook_index.yml
  pkg/idaes_examples/common/hda/__init__.py
  pkg/idaes_examples/common/hda/hda_ideal_VLE.py
  pkg/idaes_examples/common/hda/hda_reaction.py
  pkg/idaes_examples/common/methanol/methanol_ideal_VLE.py
  pkg/idaes_examples/common/methanol/methanol_ideal_vapor.py
  pkg/idaes_examples/common/methanol/methanol_reactions.py
  src/Examples/Flowsheets/HDA_flowsheet_with_costing.ipynb
  src/Examples/Flowsheets/HDA_flowsheet_with_distillation_solution_testing.ipynb
  src/Examples/Flowsheets/hda_flowsheets_for_costing_notebook.py
  src/Examples/Flowsheets/hda_reaction_kinetic.py
  src/Examples/Flowsheets/methanol_flowsheet.py
  src/Examples/Flowsheets/methanol_flowsheet_w_recycle.py
  src/Examples/Flowsheets/methanol_synthesis.ipynb
  src/Examples/Flowsheets/power_generation/ngfc/NGFC_flowsheet.py
  src/Tutorials/Basics/HDA_flowsheet_solution_testing.ipynb
  src/Tutorials/Basics/hda_ideal_VLE.py
  src/Tutorials/Basics/visualizer_tutorial.py
  src/notebook_index.ipynb
Labels: documentation, Priority:Normal
