Repository IDAES/examples-pse, pull requests merged in 2023-01, with the labels that each got.

#152 1D fixed bed adsorption/desorption example
  build-ci.yml
  build.yml
  docs/Examples/Flowsheets/CO2_adsorption_desorption/CO2_Adsorption_Desorption_figure.png
  docs/Examples/Flowsheets/CO2_adsorption_desorption/index.rst
  docs/Examples/Flowsheets/index.rst
  docs/Examples/Flowsheets/power_generation/index.rst
  docs/Examples/Flowsheets/power_generation/ngcc/gas_turbine_template.svg
  docs/Examples/Flowsheets/power_generation/ngcc/hrsg_template.svg
  docs/Examples/Flowsheets/power_generation/ngcc/index.rst
  docs/Examples/Flowsheets/power_generation/ngcc/soec_template.svg
  docs/Examples/Flowsheets/power_generation/ngcc/steam_turbine_template.svg
  docs/Examples/Flowsheets/power_generation/sofc_soec/index.rst
  docs/Examples/Flowsheets/power_generation/sofc_soec/sofc_soec_PFD.svg
  docs/Examples/Flowsheets/power_generation/subcritical/plant_pfd.svg
  docs/Examples/Flowsheets/power_generation/supercritical/Boiler_scpc_PFD.svg
  docs/Examples/Flowsheets/power_generation/supercritical/index.rst
  docs/Examples/Flowsheets/power_generation/supercritical/supercritical_steam_cycle.svg
  notebook_index.yml
  src/Examples/Flowsheets/CO2_adsorption_desorption/CO2_Adsorption_Desorption_example_1DFixedBed.ipynb
  src/Examples/Flowsheets/CO2_adsorption_desorption/CO2_Adsorption_Desorption_figure.png
  src/Examples/Flowsheets/CO2_adsorption_desorption/NETL_32D_adsorption_reactions.py
  src/Examples/Flowsheets/CO2_adsorption_desorption/NETL_32D_gas_phase_thermo.py
  src/Examples/Flowsheets/CO2_adsorption_desorption/NETL_32D_solid_phase_thermo.py
  src/Examples/Flowsheets/CO2_adsorption_desorption/__init__.py
  src/Examples/Flowsheets/CO2_adsorption_desorption/simulation_utilities.py
  src/Examples/Flowsheets/power_generation/sofc_soec/data_tabulated/sofc+soec.csv
  src/Examples/Flowsheets/power_generation/sofc_soec/sofc_soec_costing.py
  src/Examples/Flowsheets/power_generation/sofc_soec/sofc_soec_init.json.gz
  src/Examples/Flowsheets/power_generation/sofc_soec/sofc_soec_template.svg
  src/Examples/Flowsheets/power_generation/sofc_soec/sofc_with_soec.ipynb
  src/Examples/Flowsheets/power_generation/sofc_soec/sofc_with_soec.py
  src/notebook_index.ipynb
Labels: Priority:High

#172 Use More Stable Solver Calls In Surrogate Notebooks
  src/Examples/SurrMod/FlowsheetOptimization/ALAMO_flowsheet_optimization.ipynb
  src/Examples/SurrMod/FlowsheetOptimization/Best_practices_optimization.ipynb
  src/Examples/SurrMod/FlowsheetOptimization/Keras_flowsheet_optimization.ipynb
  src/Examples/SurrMod/FlowsheetOptimization/PySMO_flowsheet_optimization.ipynb
Labels: bug, Priority:EXTREME

#173 Update property metadata
  pkg/idaes_examples/common/hda/hda_ideal_VLE.py
  src/Examples/Advanced/CustomUnitModels/methanol_param_VLE.py
  src/Examples/Advanced/CustomUnitModels/methanol_state_block_VLE.py
Labels: bug, Priority:High

#174 Fixing metadata for properties in CO2 adsorption example
  src/Examples/Flowsheets/CO2_adsorption_desorption/NETL_32D_adsorption_reactions.py
  src/Examples/Flowsheets/CO2_adsorption_desorption/NETL_32D_gas_phase_thermo.py
  src/Examples/Flowsheets/CO2_adsorption_desorption/NETL_32D_solid_phase_thermo.py
Labels: bug, Priority:EXTREME
